### ISSUE TITLE
Le try...catch{...} ne remplace pas un if

### ISSUE THREAD

**Issue by r0mdau** [whatelse/Printer#1]
@thomasgheberg @vfadda : dans le fichier ExplorerClient.cs c'est du code de cochon ligne 33 :p

**Comment by thomasgheberg** [comment]
Ca me semble bon. On fait un copy, si ca fonctionne pas c'est une exeption, pas un bug car on créé le répertoire juste avant. Donc exception. Pas besoin de vérifier avant si le répertoire existe. cf le point de vue de Sylvain ^^

**Comment by r0mdau** [comment]
Je me suis chié, c'est ligne 33.
Read in english http://www.techopedia.com/definition/25641/trycatch-block.
Un try catch gère une erreur de code qui n'est pas censée se produire, pas un test pour savoir si un répertoire existe.

**Comment by thomasgheberg** [comment]
sur celui la je suis d'accord. j'ai corrigé.
